version: '3'

services:
  nest-app:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    image: nest-app
    container_name: nest-app
    ports:
      - ${PORT}:${PORT}
    environment:
      - APP_VERSION=${APP_VERSION}
      - STAGE=${STAGE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
      - HOST_API=${HOST_API}
  postgres-db:
    container_name: ${DB_NAME}
    image: postgres:15.1
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres-db:
    external: false